'use strict';
const D=JSON.parse(document.getElementById('orbit-data').textContent),$=id=>document.getElementById(id);
const categories=Object.keys(D.colors),groups=Object.fromEntries(categories.map(c=>[c,D.rows.filter(r=>r.category===c)]));
const byRow=new Map(D.rows.map(r=>[r.embedding_row,r]));
const circular=(a,b)=>Math.abs((a-b+540)%360-180);
const nearest=(c,a)=>groups[c].reduce((best,r)=>circular(r.heading,a)<circular(best.heading,a)?r:best,groups[c][0]);
const lookup=Object.fromEntries(categories.map(c=>[c,Array.from({length:360},(_,a)=>nearest(c,a))]));
const representatives=Object.fromEntries(categories.map(c=>{const seen=new Map();for(const r of groups[c])if(!seen.has(r.heading))seen.set(r.heading,r);return[c,[...seen.values()].sort((a,b)=>a.heading-b.heading)];}));
const ranges=[0,1,2].map(i=>{const v=D.rows.map(r=>r.coords[i]),lo=Math.min(...v),hi=Math.max(...v);return[lo,hi]});
const params=new URLSearchParams(location.search);
let color=categories.includes(params.get('color'))?params.get('color'):'Indigo';
let angle=Math.round(Math.max(0,Math.min(360,Number(params.get('heading'))||0)));
let mode=['3d','01','02','12'].includes(params.get('projection'))?params.get('projection'):'3d';
let selected=null,playing=false,continuous=angle,lastFrame=0,lastUpdate=0,urlTimer=0;
let yaw=-.65,pitch=.55,zoom=1,plotWidth=0,plotHeight=0,screenPoints=[],staticFrame=0;
let pendingRow=null,displayBusy=false,prefetchBusy=false,activeSheet=null;
const sheets=new Map(),loading=new Map(),MAX_SHEETS=3;
const plot=$('plot'),base=document.createElement('canvas'),overlay=document.createElement('canvas'),tooltip=document.createElement('div');
base.setAttribute('aria-hidden','true');overlay.setAttribute('role','img');overlay.setAttribute('aria-label','PCA projection; drag to rotate and click a measured view');tooltip.className='plot-tooltip';plot.append(base,overlay,tooltip);
const ctx=base.getContext('2d'),marker=overlay.getContext('2d'),preview=$('jeep-preview').getContext('2d');
const coordinateValues=[];
for(let i=0;i<3;i++){const e=document.createElement('div');e.className='coordinate';const b=document.createElement('b');b.textContent=`PC${i+1}`;const span=document.createElement('span');e.append(b,span);$('coordinates').append(e);coordinateValues.push(span);}
function syncUrl(){clearTimeout(urlTimer);urlTimer=setTimeout(()=>{const p=new URLSearchParams({color,heading:String(angle),projection:mode});history.replaceState(null,'','?'+p)},150);}
function state(){window.orbitState={heading:angle,color,mode,selectedRow:selected?.embedding_row??null,selectedHeading:selected?.heading??null,coords:selected?[...selected.coords]:[],playing,markerRow:selected?.embedding_row??null,imageRow:selected?.embedding_row??null,pendingRow:pendingRow?.embedding_row??null,previewSheets:sheets.size};}
function evict(){while(sheets.size>MAX_SHEETS){const key=[...sheets.keys()].find(k=>k!==activeSheet);if(key===undefined)break;sheets.delete(key)}}
async function loadSheet(path){if(sheets.has(path)){const img=sheets.get(path);sheets.delete(path);sheets.set(path,img);return img}if(loading.has(path))return loading.get(path);
 const job=(async()=>{const img=new Image();img.src=D.atlases?.[path]||path;await img.decode();sheets.set(path,img);evict();return img})();loading.set(path,job);try{return await job}finally{loading.delete(path)}}
function prefetch(){if(!playing||prefetchBusy||!selected)return;const next=lookup[color][(angle+15)%360];if(next.preview_sheet===selected.preview_sheet||sheets.has(next.preview_sheet))return;prefetchBusy=true;loadSheet(next.preview_sheet).catch(()=>{}).finally(()=>{prefetchBusy=false})}
function project(coords){if(mode!=='3d'){const ax=[+mode[0],+mode[1]],pad=52;return{x:pad+(coords[ax[0]]-ranges[ax[0]][0])/(ranges[ax[0]][1]-ranges[ax[0]][0])*(plotWidth-pad*2),y:plotHeight-pad-(coords[ax[1]]-ranges[ax[1]][0])/(ranges[ax[1]][1]-ranges[ax[1]][0])*(plotHeight-pad*2),depth:0}}
 const n=coords.map((v,i)=>(v-(ranges[i][0]+ranges[i][1])/2)/((ranges[i][1]-ranges[i][0])/2));const x=Math.cos(yaw)*n[0]-Math.sin(yaw)*n[1],y=Math.sin(yaw)*n[0]+Math.cos(yaw)*n[1];const z=Math.sin(pitch)*y+Math.cos(pitch)*n[2],depth=Math.cos(pitch)*y-Math.sin(pitch)*n[2],scale=Math.min(plotWidth*.28,plotHeight*.30)*zoom;return{x:plotWidth/2+x*scale,y:plotHeight/2-z*scale,depth};}
function line(a,b,color,width=1,dashed=false){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dashed?[4,5]:[]);ctx.stroke();ctx.setLineDash([])}
function axes(){ctx.font='11px system-ui';ctx.fillStyle='#a4b3c9';if(mode!=='3d'){const ax=[+mode[0],+mode[1]],pad=52;for(let i=0;i<=4;i++){const x=pad+(plotWidth-pad*2)*i/4,y=plotHeight-pad-(plotHeight-pad*2)*i/4;line({x,y:pad},{x,y:plotHeight-pad},'#263449');line({x:pad,y},{x:plotWidth-pad,y},'#263449');ctx.fillText((ranges[ax[0]][0]+(ranges[ax[0]][1]-ranges[ax[0]][0])*i/4).toFixed(2),x-12,plotHeight-pad+18);ctx.fillText((ranges[ax[1]][0]+(ranges[ax[1]][1]-ranges[ax[1]][0])*i/4).toFixed(2),8,y+4)}ctx.textAlign='center';ctx.fillText(`PC${ax[0]+1} · ${(D.ratio[ax[0]]*100).toFixed(1)}%`,plotWidth/2,plotHeight-10);ctx.save();ctx.translate(11,plotHeight/2);ctx.rotate(-Math.PI/2);ctx.fillText(`PC${ax[1]+1} · ${(D.ratio[ax[1]]*100).toFixed(1)}%`,0,0);ctx.restore();ctx.textAlign='left';return}
 const origin=ranges.map(r=>r[0]);for(let axis=0;axis<3;axis++){const end=[...origin];end[axis]=ranges[axis][1];line(project(origin),project(end),'#50627f');const p=project(end);ctx.fillText(`PC${axis+1} · ${(D.ratio[axis]*100).toFixed(1)}%`,p.x+4,p.y+4);for(let step=0;step<=4;step++){for(let other=axis+1;other<3;other++){const a=[...origin],b=[...origin];a[axis]=b[axis]=ranges[axis][0]+(ranges[axis][1]-ranges[axis][0])*step/4;b[other]=ranges[other][1];line(project(a),project(b),'#263449')}}}}
function staticPlot(){staticFrame=0;if(!plotWidth)return;ctx.clearRect(0,0,plotWidth,plotHeight);axes();const visible=$('context').checked?categories:[color];screenPoints=[];
 for(const c of visible){const active=c===color,hex=D.colors[c],rows=representatives[c];ctx.globalAlpha=active?1:.3;for(let i=1;i<rows.length;i++)line(project(rows[i-1].coords),project(rows[i].coords),hex,active?2:1,rows[i].heading-rows[i-1].heading>5);line(project(rows.at(-1).coords),project(rows[0].coords),hex,1,true);
 const points=$('cloud').checked?groups[c]:rows;ctx.globalAlpha=active?.5:.22;ctx.fillStyle=hex;for(const row of points){const p=project(row.coords);ctx.beginPath();ctx.arc(p.x,p.y,active?1.7:1.2,0,Math.PI*2);ctx.fill();screenPoints.push({...p,row})}ctx.globalAlpha=1;}
 const front=byRow.get(D.references[color]),f=project(front.coords);ctx.fillStyle='#a4b3c9';ctx.fillRect(f.x-3,f.y-3,6,6);drawMarker();}
function scheduleStatic(){if(!staticFrame)staticFrame=requestAnimationFrame(staticPlot)}
function drawMarker(){marker.clearRect(0,0,plotWidth,plotHeight);if(!selected||!plotWidth)return;const p=project(selected.coords);marker.beginPath();marker.arc(p.x,p.y,8,0,Math.PI*2);marker.fillStyle=D.colors[selected.category];marker.fill();marker.lineWidth=2;marker.strokeStyle='#fff';marker.stroke();marker.font='12px system-ui';marker.textAlign='center';marker.fillStyle='#fff';marker.fillText(`${selected.heading}°`,p.x,p.y-14);window.orbitPoint={x:p.x,y:p.y,row:selected.embedding_row};}
function resize(){const rect=plot.getBoundingClientRect(),dpr=devicePixelRatio||1;plotWidth=rect.width;plotHeight=rect.height;for(const [canvas,context] of [[base,ctx],[overlay,marker]]){canvas.width=Math.round(plotWidth*dpr);canvas.height=Math.round(plotHeight*dpr);context.setTransform(dpr,0,0,dpr,0,0)}staticPlot()}
function showRow(row,image){activeSheet=row.preview_sheet;selected=row;const cell=row.preview_cell;preview.clearRect(0,0,256,176);preview.drawImage(image,(cell%8)*256,Math.floor(cell/8)*176,256,176,0,0,256,176);$('jeep-preview').dataset.row=row.embedding_row;$('jeep-preview').setAttribute('aria-label',`${row.category} Jeep, measured relative heading ${row.heading} degrees`);
 const mismatch=circular(row.heading,angle);$('selected-view').textContent=`${row.category} · ${row.heading}°`;$('mismatch').textContent=mismatch===0?'Exact angle':`Δ ${mismatch}°`;$('image-name').textContent=row.image_path.split('/').at(-1);$('row-info').textContent=`Embedding row ${row.embedding_row} · 512 values`;row.coords.forEach((v,i)=>coordinateValues[i].textContent=v.toFixed(4));const ref=byRow.get(D.references[row.category]);$('reference-label').textContent=`Cosine to front reference (${ref.heading}°)`;$('similarity').textContent=row.cos_to_front.toFixed(4);$('view-note').textContent=row.uncertainty?`Source angle has ±${row.uncertainty}° label uncertainty.`:'Nearest measured view; no image or vector interpolation.';$('original').href=D.imageBase+row.image_path;$('status').textContent='';drawMarker();state();evict();prefetch();}
async function requestDisplay(row){pendingRow=row;if(displayBusy)return;displayBusy=true;try{while(pendingRow){const current=pendingRow;pendingRow=null;if(selected?.embedding_row===current.embedding_row){$('mismatch').textContent=circular(current.heading,angle)===0?'Exact angle':`Δ ${circular(current.heading,angle)}°`;state();prefetch();continue}$('status').textContent=sheets.has(current.preview_sheet)?'':'Loading preview…';const image=await loadSheet(current.preview_sheet);if(pendingRow&&pendingRow.embedding_row!==current.embedding_row)continue;showRow(current,image)}}catch(error){stop();$('status').textContent='Preview could not load. Move the heading to retry.';console.error(error)}finally{displayBusy=false}}
function setHeading(value,{fromPlay=false,row=null}={}){angle=Math.round(Math.max(0,Math.min(360,value)));$('heading').value=angle;$('heading-text').textContent=`${angle}°`;state();requestDisplay(row||lookup[color][angle%360]);if(!fromPlay){continuous=angle;syncUrl()}}
function variance(){const ax=mode==='3d'?[0,1,2]:[+mode[0],+mode[1]];$('variance').textContent=`${(ax.reduce((s,i)=>s+D.ratio[i],0)*100).toFixed(1)}% of embedding variation shown · fixed basis, all Jeep views`}
function stop(){playing=false;lastFrame=0;$('play').textContent='▶ Play';$('play').setAttribute('aria-pressed','false');state();syncUrl()}
function animate(now){if(!playing)return;if(lastFrame)continuous+=(now-lastFrame)/1000*Number($('speed').value);lastFrame=now;if(continuous>360)continuous%=360;if(now-lastUpdate>=1000/30){lastUpdate=now;const next=Math.round(continuous);if(next!==angle)setHeading(next,{fromPlay:true})}requestAnimationFrame(animate)}
function pickColor(next){color=next;document.documentElement.style.setProperty('--accent',D.colors[color]);for(const button of $('colors').children)button.setAttribute('aria-pressed',String(button.dataset.color===color));setHeading(angle);scheduleStatic()}
function closest(x,y){let best=null,d=14*14;for(const p of screenPoints){const distance=(p.x-x)**2+(p.y-y)**2;if(distance<d){d=distance;best=p.row}}return best}
let pointer=null;
overlay.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};overlay.setPointerCapture(e.pointerId)});
overlay.addEventListener('pointermove',e=>{const rect=overlay.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;if(pointer){const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.abs(e.clientX-pointer.startX)+Math.abs(e.clientY-pointer.startY)>2)pointer.moved=true;pointer.x=e.clientX;pointer.y=e.clientY;if(mode==='3d'){yaw+=dx*.008;pitch=Math.max(-1.3,Math.min(1.3,pitch+dy*.008));scheduleStatic()}tooltip.style.display='none';return}const row=closest(x,y);tooltip.style.display=row?'block':'none';if(row){tooltip.textContent=`${row.category} · ${row.heading}°`;tooltip.style.left=Math.min(x+12,plotWidth-110)+'px';tooltip.style.top=y+12+'px'}});
overlay.addEventListener('pointerup',e=>{const moved=pointer?.moved;pointer=null;if(moved)return;const rect=overlay.getBoundingClientRect(),row=closest(e.clientX-rect.left,e.clientY-rect.top);if(row){stop();if(row.category!==color)pickColor(row.category);setHeading(row.heading,{row})}});
overlay.addEventListener('pointercancel',()=>pointer=null);overlay.addEventListener('pointerleave',()=>tooltip.style.display='none');overlay.addEventListener('wheel',e=>{if(mode!=='3d')return;e.preventDefault();zoom=Math.max(.5,Math.min(2,zoom*(e.deltaY>0?.9:1.1)));scheduleStatic()},{passive:false});
for(const category of categories){const button=document.createElement('button');button.type='button';button.dataset.color=category;button.setAttribute('aria-label',category+' Jeep');const dot=document.createElement('span');dot.className='dot';dot.style.background=D.colors[category];button.append(dot,document.createTextNode(category));button.onclick=()=>pickColor(category);$('colors').append(button);const entry=document.createElement('span');entry.append(dot.cloneNode(),document.createTextNode(category));$('legend').append(entry);}
$('heading').oninput=e=>{if(playing)stop();setHeading(Number(e.target.value))};for(const button of document.querySelectorAll('[data-angle]'))button.onclick=()=>{stop();setHeading(Number(button.dataset.angle))};
$('play').onclick=()=>{if(playing){stop();return}playing=true;continuous=angle;lastFrame=0;lastUpdate=0;$('play').textContent='Ⅱ Pause';$('play').setAttribute('aria-pressed','true');state();prefetch();requestAnimationFrame(animate)};
$('projection').value=mode;$('projection').onchange=()=>{stop();mode=$('projection').value;variance();state();staticPlot();syncUrl()};$('context').onchange=$('cloud').onchange=scheduleStatic;$('reset').onclick=()=>{yaw=-.65;pitch=.55;zoom=1;staticPlot()};
$('labels-link').href=D.labelsUrl;$('cache-link').href=D.cacheUrl;$('methods-link').href=D.cacheUrl.replace('/tree/','/blob/').replace('/clip_embeddings','/heading_labels/README.md');document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
new ResizeObserver(resize).observe(plot);variance();pickColor(color);resize();
